name: 'Publish Github Release'

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Test
      run: dotnet test --verbosity normal
    - name: Build Windows
      run: dotnet publish ./src/Chirp.CLI/Chirp.CLI.csproj --no-restore --configuration Release -r win-x64 --no-self-contained -p:PublishSingleFile=true
    - name: Build MacOS
      run: dotnet publish ./src/Chirp.CLI/Chirp.CLI.csproj --no-restore --configuration Release -r osx-x64 --no-self-contained -p:PublishSingleFile=true
    - name: Build linux
      run: dotnet publish ./src/Chirp.CLI/Chirp.CLI.csproj --no-restore --configuration Release -r linux-x64 --no-self-contained -p:PublishSingleFile=true
    - name: Zip Files
      run: |
        cd ./src/Chirp.CLI/bin/Release/net7.0/win-x64/publish && zip ../../../../../../../Chirp.CLI-${{github.ref_name}}-win-x64.zip Chirp.CLI.exe
        cd ../../osx-x64/publish && zip ../../../../../../../Chirp.CLI-${{github.ref_name}}-osx-x64.zip Chirp.CLI
        cd ../../win-x64/publish && zip ../../../../../../../Chirp.CLI-${{github.ref_name}}-linux-x64.zip Chirp.CLI 
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Chirp.CLI-${{github.ref_name}}-win-x64.zip
          Chirp.CLI-${{github.ref_name}}-osx-x64.zip
          Chirp.CLI-${{github.ref_name}}-linux-x64.zip